
CREATE TABLE posts (
    userId INTEGER NOT NULL FOREIGN KEY,
    id INTEGER NOT NULL PRIMARY KEY,
    title VARCHAR NOT NULL,
    body VARCHAR NOT NULL,
);



CREATE TABLE comments (
    postId INTEGER NOT NULL FOREIGN KEY,
    id INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    body VARCHAR NOT NULL,
);

